# This is a basic workflow to help you get started with Actions

name: Shared workflow

# Controls when the workflow will run
on:
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import glob
            from pathlib import Path
            print("Directory contents:")
            files = list(Path(".").rglob("*.[cC][sS]"))
            print("")
            for f in files:
                print(f)
                print("---")
                file_contents = Path(f).read_text()
                print(file_contents)
                print("==========")
                print("")

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
